# Client common files
require 'ApiMktpNetshoesV1/monkey'
require 'ApiMktpNetshoesV1/client'
require 'ApiMktpNetshoesV1/client/configuration'
require 'ApiMktpNetshoesV1/client/request'
require 'ApiMktpNetshoesV1/client/response'
require 'ApiMktpNetshoesV1/client/version'

# Models
require 'ApiMktpNetshoesV1/model/base_object'
require 'ApiMktpNetshoesV1/model/attribute_resource'
require 'ApiMktpNetshoesV1/model/attribute_list_resource'
require 'ApiMktpNetshoesV1/model/image_resource'
require 'ApiMktpNetshoesV1/model/image_list_resource'
require 'ApiMktpNetshoesV1/model/product_resource'
require 'ApiMktpNetshoesV1/model/product_list_resource'
require 'ApiMktpNetshoesV1/model/link'
require 'ApiMktpNetshoesV1/model/sku_resource'
require 'ApiMktpNetshoesV1/model/sku_list_resource'
require 'ApiMktpNetshoesV1/model/stock_response'
require 'ApiMktpNetshoesV1/model/stock_resource'
require 'ApiMktpNetshoesV1/model/brand_resource'
require 'ApiMktpNetshoesV1/model/brand_list_resource'
require 'ApiMktpNetshoesV1/model/product_type_resource'
require 'ApiMktpNetshoesV1/model/product_type_list_resource'
require 'ApiMktpNetshoesV1/model/template_resource'
require 'ApiMktpNetshoesV1/model/template_list_resource'
require 'ApiMktpNetshoesV1/model/flavor_resource'
require 'ApiMktpNetshoesV1/model/flavor_list_resource'
require 'ApiMktpNetshoesV1/model/color_resource'
require 'ApiMktpNetshoesV1/model/color_list_resource'
require 'ApiMktpNetshoesV1/model/size_resource'
require 'ApiMktpNetshoesV1/model/size_list_resource'
require 'ApiMktpNetshoesV1/model/department_resource'
require 'ApiMktpNetshoesV1/model/department_list_resource'
require 'ApiMktpNetshoesV1/model/business_unit_resource'
require 'ApiMktpNetshoesV1/model/business_unit_response'
require 'ApiMktpNetshoesV1/model/issuer_resource'
require 'ApiMktpNetshoesV1/model/order_list_resource'
require 'ApiMktpNetshoesV1/model/order_resource'
require 'ApiMktpNetshoesV1/model/shipping_list_resource'
require 'ApiMktpNetshoesV1/model/shipping_resource'
require 'ApiMktpNetshoesV1/model/transport_resource'
require 'ApiMktpNetshoesV1/model/status_resource'
require 'ApiMktpNetshoesV1/model/order_item_resource'
require 'ApiMktpNetshoesV1/model/devolution_item_resource'
require 'ApiMktpNetshoesV1/model/invoice_resource'
require 'ApiMktpNetshoesV1/model/customer_resource'
require 'ApiMktpNetshoesV1/model/customer_address_resource'
require 'ApiMktpNetshoesV1/model/price_resource'
require 'ApiMktpNetshoesV1/model/price_schedule_resource'
require 'ApiMktpNetshoesV1/model/price_list'
require 'ApiMktpNetshoesV1/model/error_resource'

# APIs
require 'ApiMktpNetshoesV1/api/products_api'
require 'ApiMktpNetshoesV1/api/skus_api'
require 'ApiMktpNetshoesV1/api/orders_api'
require 'ApiMktpNetshoesV1/api/products_templates_api'

module ApiMktpNetshoesV1
  # Initialize the default configuration
  Client.configuration ||= Client::Configuration.new
end
